# Generated by Django 3.1.2 on 2020-10-24 21:25

from django.db import migrations
import stevenlsjr_blog.cms.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('stevenlsjr_cms', '0002_auto_20200823_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('rich_text', stevenlsjr_blog.cms.blocks.RichTextBlock()), ('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]),
        ),
    ]
