apiVersion: v1
kind: Service
metadata:
  name: {{ include "stevenlsjr-blog-server.fullname"  . }}-staticfiles
  labels:
    {{- include "stevenlsjr-blog-server.staticfilesLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stevenlsjr-blog-server.staticfilesSelectorLabels" . | nindent 4 }}
