version: "2.1"
commands:
  install_buildx:
    description: setup docker buildx
    steps:
      - run: apk add make curl
      - run: mkdir -vp ~/.docker/cli-plugins/
      - run: curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
      - run: chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run: docker buildx version
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:
          version: 19.03.12
      - install_buildx
      - run:
          name: Docker login
          command: |
             echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      