version: "2.1"
workflows:
  build:
    jobs:
      - build-images:
          context: "steve's context"

jobs:
  build-images:
    docker:
      - image: stevenlsjr/docker:latest
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:
          version: '19.03.12'
      - run:
          name: Docker login
          command: |
             echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
      - run: |
         docker buildx create cicontext --use \
          --driver docker-container \
          --driver-opt image=moby/buildkit:master,network=host
      - run:
          name: Build server
          command: |
            docker buildx build \
              -t stevenlsjr/blog-server:latest    \
              --platform=linux/amd64,linux/arm64  \
              --push                              \
              -f deploy/blog-server.dockerfile    \
              .